# Generated by Django 4.0.5 on 2022-06-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetails',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productby', to='api.product'),
        ),
        migrations.AlterField(
            model_name='salesdetails',
            name='salesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesby', to='api.sales'),
        ),
    ]
